//
// Created by sibirsky on 30.05.18.
//

#ifndef FIRSTPROJECT_IMAGECONSTANTS_H
#define FIRSTPROJECT_IMAGECONSTANTS_H

#define IMG_ROI_WIDTH 40
#define IMG_ROI_HEIGHT 40
#define IMG_MAX_WIDTH 1280
#define IMG_MAX_HEIGHT 720

#endif //FIRSTPROJECT_IMAGECONSTANTS_H
